// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: call_audit/call_questionnaire_rule.proto

package call_audit

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message: CallQuestionnaireRule
type CallQuestionnaireRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId         int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy        *Lookup                `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy        *Lookup                `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Name             string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	LanguageProfile  *Lookup                `protobuf:"bytes,8,opt,name=language_profile,json=languageProfile,proto3" json:"language_profile,omitempty"`
	Description      string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Enabled          bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CognitiveProfile *Lookup                `protobuf:"bytes,11,opt,name=cognitive_profile,json=cognitiveProfile,proto3" json:"cognitive_profile,omitempty"`
	From             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=to,proto3" json:"to,omitempty"`
	CallDirection    string                 `protobuf:"bytes,14,opt,name=call_direction,json=callDirection,proto3" json:"call_direction,omitempty"`
	MinCallDuration  int32                  `protobuf:"varint,15,opt,name=min_call_duration,json=minCallDuration,proto3" json:"min_call_duration,omitempty"`
	Variable         string                 `protobuf:"bytes,16,opt,name=variable,proto3" json:"variable,omitempty"`
	DefaultPromt     string                 `protobuf:"bytes,17,opt,name=default_promt,json=defaultPromt,proto3" json:"default_promt,omitempty"`
	SaveExplanation  bool                   `protobuf:"varint,18,opt,name=save_explanation,json=saveExplanation,proto3" json:"save_explanation,omitempty"`
	LastStoredAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=last_stored_at,json=lastStoredAt,proto3" json:"last_stored_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallQuestionnaireRule) Reset() {
	*x = CallQuestionnaireRule{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallQuestionnaireRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallQuestionnaireRule) ProtoMessage() {}

func (x *CallQuestionnaireRule) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallQuestionnaireRule.ProtoReflect.Descriptor instead.
func (*CallQuestionnaireRule) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{0}
}

func (x *CallQuestionnaireRule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallQuestionnaireRule) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *CallQuestionnaireRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CallQuestionnaireRule) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *CallQuestionnaireRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CallQuestionnaireRule) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *CallQuestionnaireRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallQuestionnaireRule) GetLanguageProfile() *Lookup {
	if x != nil {
		return x.LanguageProfile
	}
	return nil
}

func (x *CallQuestionnaireRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CallQuestionnaireRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CallQuestionnaireRule) GetCognitiveProfile() *Lookup {
	if x != nil {
		return x.CognitiveProfile
	}
	return nil
}

func (x *CallQuestionnaireRule) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CallQuestionnaireRule) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CallQuestionnaireRule) GetCallDirection() string {
	if x != nil {
		return x.CallDirection
	}
	return ""
}

func (x *CallQuestionnaireRule) GetMinCallDuration() int32 {
	if x != nil {
		return x.MinCallDuration
	}
	return 0
}

func (x *CallQuestionnaireRule) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

func (x *CallQuestionnaireRule) GetDefaultPromt() string {
	if x != nil {
		return x.DefaultPromt
	}
	return ""
}

func (x *CallQuestionnaireRule) GetSaveExplanation() bool {
	if x != nil {
		return x.SaveExplanation
	}
	return false
}

func (x *CallQuestionnaireRule) GetLastStoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStoredAt
	}
	return nil
}

// Message: CallQuestionnaireRuleList
type CallQuestionnaireRuleList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CallQuestionnaireRule `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Next          bool                     `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallQuestionnaireRuleList) Reset() {
	*x = CallQuestionnaireRuleList{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallQuestionnaireRuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallQuestionnaireRuleList) ProtoMessage() {}

func (x *CallQuestionnaireRuleList) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallQuestionnaireRuleList.ProtoReflect.Descriptor instead.
func (*CallQuestionnaireRuleList) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{1}
}

func (x *CallQuestionnaireRuleList) GetItems() []*CallQuestionnaireRule {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CallQuestionnaireRuleList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CallQuestionnaireRuleList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// Message: GetByIdRequest
type GetCallQuestionnaireRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallQuestionnaireRuleRequest) Reset() {
	*x = GetCallQuestionnaireRuleRequest{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallQuestionnaireRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallQuestionnaireRuleRequest) ProtoMessage() {}

func (x *GetCallQuestionnaireRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallQuestionnaireRuleRequest.ProtoReflect.Descriptor instead.
func (*GetCallQuestionnaireRuleRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{2}
}

func (x *GetCallQuestionnaireRuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Message: DeleteByIdRequest
type DeleteCallQuestionnaireRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCallQuestionnaireRuleRequest) Reset() {
	*x = DeleteCallQuestionnaireRuleRequest{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCallQuestionnaireRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCallQuestionnaireRuleRequest) ProtoMessage() {}

func (x *DeleteCallQuestionnaireRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCallQuestionnaireRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteCallQuestionnaireRuleRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCallQuestionnaireRuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Message: Create/Update Request
type UpsertCallQuestionnaireRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *CallQuestionnaireRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCallQuestionnaireRuleRequest) Reset() {
	*x = UpsertCallQuestionnaireRuleRequest{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCallQuestionnaireRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCallQuestionnaireRuleRequest) ProtoMessage() {}

func (x *UpsertCallQuestionnaireRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCallQuestionnaireRuleRequest.ProtoReflect.Descriptor instead.
func (*UpsertCallQuestionnaireRuleRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertCallQuestionnaireRuleRequest) GetRule() *CallQuestionnaireRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// Message: Empty
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_call_questionnaire_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_call_audit_call_questionnaire_rule_proto_rawDescGZIP(), []int{5}
}

var File_call_audit_call_questionnaire_rule_proto protoreflect.FileDescriptor

const file_call_audit_call_questionnaire_rule_proto_rawDesc = "" +
	"\n" +
	"(call_audit/call_questionnaire_rule.proto\x12\n" +
	"call_audit\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18call_audit/general.proto\"\xcd\x06\n" +
	"\x15CallQuestionnaireRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\n" +
	"created_by\x18\x04 \x01(\v2\x12.call_audit.LookupR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x121\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\v2\x12.call_audit.LookupR\tupdatedBy\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12=\n" +
	"\x10language_profile\x18\b \x01(\v2\x12.call_audit.LookupR\x0flanguageProfile\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12?\n" +
	"\x11cognitive_profile\x18\v \x01(\v2\x12.call_audit.LookupR\x10cognitiveProfile\x12.\n" +
	"\x04from\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12%\n" +
	"\x0ecall_direction\x18\x0e \x01(\tR\rcallDirection\x12*\n" +
	"\x11min_call_duration\x18\x0f \x01(\x05R\x0fminCallDuration\x12\x1a\n" +
	"\bvariable\x18\x10 \x01(\tR\bvariable\x12#\n" +
	"\rdefault_promt\x18\x11 \x01(\tR\fdefaultPromt\x12)\n" +
	"\x10save_explanation\x18\x12 \x01(\bR\x0fsaveExplanation\x12@\n" +
	"\x0elast_stored_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\flastStoredAt\"|\n" +
	"\x19CallQuestionnaireRuleList\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.call_audit.CallQuestionnaireRuleR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04next\x18\x03 \x01(\bR\x04next\"1\n" +
	"\x1fGetCallQuestionnaireRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"4\n" +
	"\"DeleteCallQuestionnaireRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"[\n" +
	"\"UpsertCallQuestionnaireRuleRequest\x125\n" +
	"\x04rule\x18\x01 \x01(\v2!.call_audit.CallQuestionnaireRuleR\x04rule\"\a\n" +
	"\x05Empty2\xce\x03\n" +
	"\x1cCallQuestionnaireRuleService\x12U\n" +
	"\x03Get\x12+.call_audit.GetCallQuestionnaireRuleRequest\x1a!.call_audit.CallQuestionnaireRule\x12@\n" +
	"\x04List\x12\x11.call_audit.Empty\x1a%.call_audit.CallQuestionnaireRuleList\x12[\n" +
	"\x06Create\x12..call_audit.UpsertCallQuestionnaireRuleRequest\x1a!.call_audit.CallQuestionnaireRule\x12[\n" +
	"\x06Update\x12..call_audit.UpsertCallQuestionnaireRuleRequest\x1a!.call_audit.CallQuestionnaireRule\x12[\n" +
	"\x06Delete\x12..call_audit.DeleteCallQuestionnaireRuleRequest\x1a!.call_audit.CallQuestionnaireRuleB\xa4\x01\n" +
	"\x0ecom.call_auditB\x1aCallQuestionnaireRuleProtoP\x01Z2github.com/webitel/call_audit/api/call_audit\xa2\x02\x03CXX\xaa\x02\tCallAudit\xca\x02\tCallAudit\xe2\x02\x15CallAudit\\GPBMetadata\xea\x02\tCallAuditb\x06proto3"

var (
	file_call_audit_call_questionnaire_rule_proto_rawDescOnce sync.Once
	file_call_audit_call_questionnaire_rule_proto_rawDescData []byte
)

func file_call_audit_call_questionnaire_rule_proto_rawDescGZIP() []byte {
	file_call_audit_call_questionnaire_rule_proto_rawDescOnce.Do(func() {
		file_call_audit_call_questionnaire_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_call_audit_call_questionnaire_rule_proto_rawDesc), len(file_call_audit_call_questionnaire_rule_proto_rawDesc)))
	})
	return file_call_audit_call_questionnaire_rule_proto_rawDescData
}

var file_call_audit_call_questionnaire_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_call_audit_call_questionnaire_rule_proto_goTypes = []any{
	(*CallQuestionnaireRule)(nil),              // 0: call_audit.CallQuestionnaireRule
	(*CallQuestionnaireRuleList)(nil),          // 1: call_audit.CallQuestionnaireRuleList
	(*GetCallQuestionnaireRuleRequest)(nil),    // 2: call_audit.GetCallQuestionnaireRuleRequest
	(*DeleteCallQuestionnaireRuleRequest)(nil), // 3: call_audit.DeleteCallQuestionnaireRuleRequest
	(*UpsertCallQuestionnaireRuleRequest)(nil), // 4: call_audit.UpsertCallQuestionnaireRuleRequest
	(*Empty)(nil),                 // 5: call_audit.Empty
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*Lookup)(nil),                // 7: call_audit.Lookup
}
var file_call_audit_call_questionnaire_rule_proto_depIdxs = []int32{
	6,  // 0: call_audit.CallQuestionnaireRule.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: call_audit.CallQuestionnaireRule.created_by:type_name -> call_audit.Lookup
	6,  // 2: call_audit.CallQuestionnaireRule.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: call_audit.CallQuestionnaireRule.updated_by:type_name -> call_audit.Lookup
	7,  // 4: call_audit.CallQuestionnaireRule.language_profile:type_name -> call_audit.Lookup
	7,  // 5: call_audit.CallQuestionnaireRule.cognitive_profile:type_name -> call_audit.Lookup
	6,  // 6: call_audit.CallQuestionnaireRule.from:type_name -> google.protobuf.Timestamp
	6,  // 7: call_audit.CallQuestionnaireRule.to:type_name -> google.protobuf.Timestamp
	6,  // 8: call_audit.CallQuestionnaireRule.last_stored_at:type_name -> google.protobuf.Timestamp
	0,  // 9: call_audit.CallQuestionnaireRuleList.items:type_name -> call_audit.CallQuestionnaireRule
	0,  // 10: call_audit.UpsertCallQuestionnaireRuleRequest.rule:type_name -> call_audit.CallQuestionnaireRule
	2,  // 11: call_audit.CallQuestionnaireRuleService.Get:input_type -> call_audit.GetCallQuestionnaireRuleRequest
	5,  // 12: call_audit.CallQuestionnaireRuleService.List:input_type -> call_audit.Empty
	4,  // 13: call_audit.CallQuestionnaireRuleService.Create:input_type -> call_audit.UpsertCallQuestionnaireRuleRequest
	4,  // 14: call_audit.CallQuestionnaireRuleService.Update:input_type -> call_audit.UpsertCallQuestionnaireRuleRequest
	3,  // 15: call_audit.CallQuestionnaireRuleService.Delete:input_type -> call_audit.DeleteCallQuestionnaireRuleRequest
	0,  // 16: call_audit.CallQuestionnaireRuleService.Get:output_type -> call_audit.CallQuestionnaireRule
	1,  // 17: call_audit.CallQuestionnaireRuleService.List:output_type -> call_audit.CallQuestionnaireRuleList
	0,  // 18: call_audit.CallQuestionnaireRuleService.Create:output_type -> call_audit.CallQuestionnaireRule
	0,  // 19: call_audit.CallQuestionnaireRuleService.Update:output_type -> call_audit.CallQuestionnaireRule
	0,  // 20: call_audit.CallQuestionnaireRuleService.Delete:output_type -> call_audit.CallQuestionnaireRule
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_call_audit_call_questionnaire_rule_proto_init() }
func file_call_audit_call_questionnaire_rule_proto_init() {
	if File_call_audit_call_questionnaire_rule_proto != nil {
		return
	}
	file_call_audit_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_call_audit_call_questionnaire_rule_proto_rawDesc), len(file_call_audit_call_questionnaire_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_call_audit_call_questionnaire_rule_proto_goTypes,
		DependencyIndexes: file_call_audit_call_questionnaire_rule_proto_depIdxs,
		MessageInfos:      file_call_audit_call_questionnaire_rule_proto_msgTypes,
	}.Build()
	File_call_audit_call_questionnaire_rule_proto = out.File
	file_call_audit_call_questionnaire_rule_proto_goTypes = nil
	file_call_audit_call_questionnaire_rule_proto_depIdxs = nil
}
