// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: call_audit/call_questionnaire_rule.proto

package call_audit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallQuestionnaireRuleService_Get_FullMethodName    = "/call_audit.CallQuestionnaireRuleService/Get"
	CallQuestionnaireRuleService_List_FullMethodName   = "/call_audit.CallQuestionnaireRuleService/List"
	CallQuestionnaireRuleService_Create_FullMethodName = "/call_audit.CallQuestionnaireRuleService/Create"
	CallQuestionnaireRuleService_Update_FullMethodName = "/call_audit.CallQuestionnaireRuleService/Update"
	CallQuestionnaireRuleService_Delete_FullMethodName = "/call_audit.CallQuestionnaireRuleService/Delete"
)

// CallQuestionnaireRuleServiceClient is the client API for CallQuestionnaireRuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type CallQuestionnaireRuleServiceClient interface {
	Get(ctx context.Context, in *GetCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CallQuestionnaireRuleList, error)
	Create(ctx context.Context, in *UpsertCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error)
	Update(ctx context.Context, in *UpsertCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error)
	Delete(ctx context.Context, in *DeleteCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error)
}

type callQuestionnaireRuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallQuestionnaireRuleServiceClient(cc grpc.ClientConnInterface) CallQuestionnaireRuleServiceClient {
	return &callQuestionnaireRuleServiceClient{cc}
}

func (c *callQuestionnaireRuleServiceClient) Get(ctx context.Context, in *GetCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallQuestionnaireRule)
	err := c.cc.Invoke(ctx, CallQuestionnaireRuleService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callQuestionnaireRuleServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CallQuestionnaireRuleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallQuestionnaireRuleList)
	err := c.cc.Invoke(ctx, CallQuestionnaireRuleService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callQuestionnaireRuleServiceClient) Create(ctx context.Context, in *UpsertCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallQuestionnaireRule)
	err := c.cc.Invoke(ctx, CallQuestionnaireRuleService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callQuestionnaireRuleServiceClient) Update(ctx context.Context, in *UpsertCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallQuestionnaireRule)
	err := c.cc.Invoke(ctx, CallQuestionnaireRuleService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callQuestionnaireRuleServiceClient) Delete(ctx context.Context, in *DeleteCallQuestionnaireRuleRequest, opts ...grpc.CallOption) (*CallQuestionnaireRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallQuestionnaireRule)
	err := c.cc.Invoke(ctx, CallQuestionnaireRuleService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallQuestionnaireRuleServiceServer is the server API for CallQuestionnaireRuleService service.
// All implementations must embed UnimplementedCallQuestionnaireRuleServiceServer
// for forward compatibility.
//
// Service definition
type CallQuestionnaireRuleServiceServer interface {
	Get(context.Context, *GetCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error)
	List(context.Context, *Empty) (*CallQuestionnaireRuleList, error)
	Create(context.Context, *UpsertCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error)
	Update(context.Context, *UpsertCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error)
	Delete(context.Context, *DeleteCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error)
	mustEmbedUnimplementedCallQuestionnaireRuleServiceServer()
}

// UnimplementedCallQuestionnaireRuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallQuestionnaireRuleServiceServer struct{}

func (UnimplementedCallQuestionnaireRuleServiceServer) Get(context.Context, *GetCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCallQuestionnaireRuleServiceServer) List(context.Context, *Empty) (*CallQuestionnaireRuleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCallQuestionnaireRuleServiceServer) Create(context.Context, *UpsertCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCallQuestionnaireRuleServiceServer) Update(context.Context, *UpsertCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCallQuestionnaireRuleServiceServer) Delete(context.Context, *DeleteCallQuestionnaireRuleRequest) (*CallQuestionnaireRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCallQuestionnaireRuleServiceServer) mustEmbedUnimplementedCallQuestionnaireRuleServiceServer() {
}
func (UnimplementedCallQuestionnaireRuleServiceServer) testEmbeddedByValue() {}

// UnsafeCallQuestionnaireRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallQuestionnaireRuleServiceServer will
// result in compilation errors.
type UnsafeCallQuestionnaireRuleServiceServer interface {
	mustEmbedUnimplementedCallQuestionnaireRuleServiceServer()
}

func RegisterCallQuestionnaireRuleServiceServer(s grpc.ServiceRegistrar, srv CallQuestionnaireRuleServiceServer) {
	// If the following call pancis, it indicates UnimplementedCallQuestionnaireRuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallQuestionnaireRuleService_ServiceDesc, srv)
}

func _CallQuestionnaireRuleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallQuestionnaireRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallQuestionnaireRuleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallQuestionnaireRuleService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallQuestionnaireRuleServiceServer).Get(ctx, req.(*GetCallQuestionnaireRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallQuestionnaireRuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallQuestionnaireRuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallQuestionnaireRuleService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallQuestionnaireRuleServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallQuestionnaireRuleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCallQuestionnaireRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallQuestionnaireRuleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallQuestionnaireRuleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallQuestionnaireRuleServiceServer).Create(ctx, req.(*UpsertCallQuestionnaireRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallQuestionnaireRuleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCallQuestionnaireRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallQuestionnaireRuleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallQuestionnaireRuleService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallQuestionnaireRuleServiceServer).Update(ctx, req.(*UpsertCallQuestionnaireRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallQuestionnaireRuleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCallQuestionnaireRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallQuestionnaireRuleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallQuestionnaireRuleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallQuestionnaireRuleServiceServer).Delete(ctx, req.(*DeleteCallQuestionnaireRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallQuestionnaireRuleService_ServiceDesc is the grpc.ServiceDesc for CallQuestionnaireRuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallQuestionnaireRuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "call_audit.CallQuestionnaireRuleService",
	HandlerType: (*CallQuestionnaireRuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CallQuestionnaireRuleService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CallQuestionnaireRuleService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CallQuestionnaireRuleService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CallQuestionnaireRuleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CallQuestionnaireRuleService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "call_audit/call_questionnaire_rule.proto",
}
