// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: call_audit/general.proto

package call_audit

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lookup) Reset() {
	*x = Lookup{}
	mi := &file_call_audit_general_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lookup) ProtoMessage() {}

func (x *Lookup) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_general_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lookup.ProtoReflect.Descriptor instead.
func (*Lookup) Descriptor() ([]byte, []int) {
	return file_call_audit_general_proto_rawDescGZIP(), []int{0}
}

func (x *Lookup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtendedLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedLookup) Reset() {
	*x = ExtendedLookup{}
	mi := &file_call_audit_general_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedLookup) ProtoMessage() {}

func (x *ExtendedLookup) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_general_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedLookup.ProtoReflect.Descriptor instead.
func (*ExtendedLookup) Descriptor() ([]byte, []int) {
	return file_call_audit_general_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendedLookup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExtendedLookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtendedLookup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_call_audit_general_proto protoreflect.FileDescriptor

const file_call_audit_general_proto_rawDesc = "" +
	"\n" +
	"\x18call_audit/general.proto\x12\n" +
	"call_audit\",\n" +
	"\x06Lookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x0eExtendedLookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeB\x96\x01\n" +
	"\x0ecom.call_auditB\fGeneralProtoP\x01Z2github.com/webitel/call_audit/api/call_audit\xa2\x02\x03CXX\xaa\x02\tCallAudit\xca\x02\tCallAudit\xe2\x02\x15CallAudit\\GPBMetadata\xea\x02\tCallAuditb\x06proto3"

var (
	file_call_audit_general_proto_rawDescOnce sync.Once
	file_call_audit_general_proto_rawDescData []byte
)

func file_call_audit_general_proto_rawDescGZIP() []byte {
	file_call_audit_general_proto_rawDescOnce.Do(func() {
		file_call_audit_general_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_call_audit_general_proto_rawDesc), len(file_call_audit_general_proto_rawDesc)))
	})
	return file_call_audit_general_proto_rawDescData
}

var file_call_audit_general_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_call_audit_general_proto_goTypes = []any{
	(*Lookup)(nil),         // 0: call_audit.Lookup
	(*ExtendedLookup)(nil), // 1: call_audit.ExtendedLookup
}
var file_call_audit_general_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_call_audit_general_proto_init() }
func file_call_audit_general_proto_init() {
	if File_call_audit_general_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_call_audit_general_proto_rawDesc), len(file_call_audit_general_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_call_audit_general_proto_goTypes,
		DependencyIndexes: file_call_audit_general_proto_depIdxs,
		MessageInfos:      file_call_audit_general_proto_msgTypes,
	}.Build()
	File_call_audit_general_proto = out.File
	file_call_audit_general_proto_goTypes = nil
	file_call_audit_general_proto_depIdxs = nil
}
