// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: call_audit/language_profiles.proto

package call_audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LanguageProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int32                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	Type          int32                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageProfile) Reset() {
	*x = LanguageProfile{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageProfile) ProtoMessage() {}

func (x *LanguageProfile) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageProfile.ProtoReflect.Descriptor instead.
func (*LanguageProfile) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *LanguageProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LanguageProfile) GetDomainId() int32 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *LanguageProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LanguageProfile) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *LanguageProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LanguageProfile) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *LanguageProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageProfile) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LanguageProfile) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetLanguageProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageProfileRequest) Reset() {
	*x = GetLanguageProfileRequest{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageProfileRequest) ProtoMessage() {}

func (x *GetLanguageProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageProfileRequest.ProtoReflect.Descriptor instead.
func (*GetLanguageProfileRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *GetLanguageProfileRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLanguageProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int32                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguageProfilesRequest) Reset() {
	*x = ListLanguageProfilesRequest{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguageProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguageProfilesRequest) ProtoMessage() {}

func (x *ListLanguageProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguageProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguageProfilesRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *ListLanguageProfilesRequest) GetDomainId() int32 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *ListLanguageProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLanguageProfilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateLanguageProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int32                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLanguageProfileRequest) Reset() {
	*x = CreateLanguageProfileRequest{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLanguageProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLanguageProfileRequest) ProtoMessage() {}

func (x *CreateLanguageProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLanguageProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateLanguageProfileRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLanguageProfileRequest) GetDomainId() int32 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *CreateLanguageProfileRequest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateLanguageProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLanguageProfileRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateLanguageProfileRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type UpdateLanguageProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,2,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLanguageProfileRequest) Reset() {
	*x = UpdateLanguageProfileRequest{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLanguageProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLanguageProfileRequest) ProtoMessage() {}

func (x *UpdateLanguageProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLanguageProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateLanguageProfileRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLanguageProfileRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLanguageProfileRequest) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *UpdateLanguageProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLanguageProfileRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateLanguageProfileRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DeleteLanguageProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLanguageProfileRequest) Reset() {
	*x = DeleteLanguageProfileRequest{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLanguageProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLanguageProfileRequest) ProtoMessage() {}

func (x *DeleteLanguageProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLanguageProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteLanguageProfileRequest) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLanguageProfileRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLanguageProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*LanguageProfile     `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguageProfilesResponse) Reset() {
	*x = ListLanguageProfilesResponse{}
	mi := &file_call_audit_language_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguageProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguageProfilesResponse) ProtoMessage() {}

func (x *ListLanguageProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_call_audit_language_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguageProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguageProfilesResponse) Descriptor() ([]byte, []int) {
	return file_call_audit_language_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *ListLanguageProfilesResponse) GetProfiles() []*LanguageProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_call_audit_language_profiles_proto protoreflect.FileDescriptor

const file_call_audit_language_profiles_proto_rawDesc = "" +
	"\n" +
	"\"call_audit/language_profiles.proto\x12\n" +
	"call_audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\x0fLanguageProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x05R\bdomainId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x03R\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\x03R\tupdatedBy\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x12\n" +
	"\x04type\x18\t \x01(\x05R\x04type\"+\n" +
	"\x19GetLanguageProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"h\n" +
	"\x1bListLanguageProfilesRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x05R\bdomainId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x98\x01\n" +
	"\x1cCreateLanguageProfileRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x05R\bdomainId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\x03R\tcreatedBy\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"\x8b\x01\n" +
	"\x1cUpdateLanguageProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x02 \x01(\x03R\tupdatedBy\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\".\n" +
	"\x1cDeleteLanguageProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"W\n" +
	"\x1cListLanguageProfilesResponse\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.call_audit.LanguageProfileR\bprofiles2\xb1\x03\n" +
	"\x16LanguageProfileService\x12I\n" +
	"\x03Get\x12%.call_audit.GetLanguageProfileRequest\x1a\x1b.call_audit.LanguageProfile\x12Y\n" +
	"\x04List\x12'.call_audit.ListLanguageProfilesRequest\x1a(.call_audit.ListLanguageProfilesResponse\x12O\n" +
	"\x06Create\x12(.call_audit.CreateLanguageProfileRequest\x1a\x1b.call_audit.LanguageProfile\x12O\n" +
	"\x06Update\x12(.call_audit.UpdateLanguageProfileRequest\x1a\x1b.call_audit.LanguageProfile\x12O\n" +
	"\x06Delete\x12(.call_audit.DeleteLanguageProfileRequest\x1a\x1b.call_audit.LanguageProfileB\x9f\x01\n" +
	"\x0ecom.call_auditB\x15LanguageProfilesProtoP\x01Z2github.com/VoroniakPavlo/call_audit/api/call_audit\xa2\x02\x03CXX\xaa\x02\tCallAudit\xca\x02\tCallAudit\xe2\x02\x15CallAudit\\GPBMetadata\xea\x02\tCallAuditb\x06proto3"

var (
	file_call_audit_language_profiles_proto_rawDescOnce sync.Once
	file_call_audit_language_profiles_proto_rawDescData []byte
)

func file_call_audit_language_profiles_proto_rawDescGZIP() []byte {
	file_call_audit_language_profiles_proto_rawDescOnce.Do(func() {
		file_call_audit_language_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_call_audit_language_profiles_proto_rawDesc), len(file_call_audit_language_profiles_proto_rawDesc)))
	})
	return file_call_audit_language_profiles_proto_rawDescData
}

var file_call_audit_language_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_call_audit_language_profiles_proto_goTypes = []any{
	(*LanguageProfile)(nil),              // 0: call_audit.LanguageProfile
	(*GetLanguageProfileRequest)(nil),    // 1: call_audit.GetLanguageProfileRequest
	(*ListLanguageProfilesRequest)(nil),  // 2: call_audit.ListLanguageProfilesRequest
	(*CreateLanguageProfileRequest)(nil), // 3: call_audit.CreateLanguageProfileRequest
	(*UpdateLanguageProfileRequest)(nil), // 4: call_audit.UpdateLanguageProfileRequest
	(*DeleteLanguageProfileRequest)(nil), // 5: call_audit.DeleteLanguageProfileRequest
	(*ListLanguageProfilesResponse)(nil), // 6: call_audit.ListLanguageProfilesResponse
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_call_audit_language_profiles_proto_depIdxs = []int32{
	7, // 0: call_audit.LanguageProfile.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: call_audit.LanguageProfile.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: call_audit.ListLanguageProfilesResponse.profiles:type_name -> call_audit.LanguageProfile
	1, // 3: call_audit.LanguageProfileService.Get:input_type -> call_audit.GetLanguageProfileRequest
	2, // 4: call_audit.LanguageProfileService.List:input_type -> call_audit.ListLanguageProfilesRequest
	3, // 5: call_audit.LanguageProfileService.Create:input_type -> call_audit.CreateLanguageProfileRequest
	4, // 6: call_audit.LanguageProfileService.Update:input_type -> call_audit.UpdateLanguageProfileRequest
	5, // 7: call_audit.LanguageProfileService.Delete:input_type -> call_audit.DeleteLanguageProfileRequest
	0, // 8: call_audit.LanguageProfileService.Get:output_type -> call_audit.LanguageProfile
	6, // 9: call_audit.LanguageProfileService.List:output_type -> call_audit.ListLanguageProfilesResponse
	0, // 10: call_audit.LanguageProfileService.Create:output_type -> call_audit.LanguageProfile
	0, // 11: call_audit.LanguageProfileService.Update:output_type -> call_audit.LanguageProfile
	0, // 12: call_audit.LanguageProfileService.Delete:output_type -> call_audit.LanguageProfile
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_call_audit_language_profiles_proto_init() }
func file_call_audit_language_profiles_proto_init() {
	if File_call_audit_language_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_call_audit_language_profiles_proto_rawDesc), len(file_call_audit_language_profiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_call_audit_language_profiles_proto_goTypes,
		DependencyIndexes: file_call_audit_language_profiles_proto_depIdxs,
		MessageInfos:      file_call_audit_language_profiles_proto_msgTypes,
	}.Build()
	File_call_audit_language_profiles_proto = out.File
	file_call_audit_language_profiles_proto_goTypes = nil
	file_call_audit_language_profiles_proto_depIdxs = nil
}
