// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package call_audit

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"CallQuestionnaireRuleService": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"Get": WebitelMethod{
				Access: 0,
				Input:  "GetCallQuestionnaireRuleRequest",
				Output: "CallQuestionnaireRule",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"List": WebitelMethod{
				Access: 0,
				Input:  "Empty",
				Output: "CallQuestionnaireRuleList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Create": WebitelMethod{
				Access: 0,
				Input:  "UpsertCallQuestionnaireRuleRequest",
				Output: "CallQuestionnaireRule",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Update": WebitelMethod{
				Access: 0,
				Input:  "UpsertCallQuestionnaireRuleRequest",
				Output: "CallQuestionnaireRule",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Delete": WebitelMethod{
				Access: 0,
				Input:  "DeleteCallQuestionnaireRuleRequest",
				Output: "CallQuestionnaireRule",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
		},
	},
	"LanguageProfileService": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"Get": WebitelMethod{
				Access: 0,
				Input:  "GetLanguageProfileRequest",
				Output: "GetLanguageProfileResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"List": WebitelMethod{
				Access: 0,
				Input:  "ListLanguageProfilesRequest",
				Output: "ListLanguageProfilesResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Create": WebitelMethod{
				Access: 0,
				Input:  "CreateLanguageProfileRequest",
				Output: "CreateLanguageProfileResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Update": WebitelMethod{
				Access: 0,
				Input:  "UpdateLanguageProfileRequest",
				Output: "UpdateLanguageProfileResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
			"Delete": WebitelMethod{
				Access: 0,
				Input:  "DeleteLanguageProfileRequest",
				Output: "DeleteLanguageProfileResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "",
						Method: "",
					},
				},
			},
		},
	},
}
